services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./api:/api
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network

  php:
    image: php:fpm-alpine
    volumes:
      - ./api:/api
    networks:
      - code-network

  symfony:
    image: symfonycorp/cli:latest
    command: symfony server:start
    volumes:
      - ./symfony:/symfony
    networks:
      - code-network
    depends_on:
      - php

  app:
    build:
      context: ./app/
    command: yarn start
    volumes:
      - ./app/:/usr/app
      - ./app/node_modules:/usr/app/node_modules
    ports:
      - "3000:3000"

networks:
  code-network:
    driver: bridge