version: '1'

services:
  web: nginx:latest
  ports:
    - "8080:80"
  volumes:

  networks:
    - code-network

  php:
    image: php:fpm
    volumes:
      - ./api:/api
    networks:
      - code-network

  app:
    build:
      context: ./app/
    command: yarn start
    volumes:
      - ./app/:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"

networks:
  code-network:
    driver: bridge